use strum::EnumIter;
use windows::Win32::UI::Input::{KeyboardAndMouse::VIRTUAL_KEY, *};

#[derive(EnumIter, Debug, Copy, Clone, Eq, PartialEq, Hash)]
pub enum KeyCode {
  Unknown = 0,
  // ASCII
  Tab = 9,
  Enter = 10,
  Space = 32,
  Apostrophe = 39,
  Comma = 44,
  Minus = 45,
  Period = 46,
  ForwardSlash = 47,
  _0 = 48,
  _1 = 49,
  _2 = 50,
  _3 = 51,
  _4 = 52,
  _5 = 53,
  _6 = 54,
  _7 = 55,
  _8 = 56,
  _9 = 57,
  Semicolon = 59,
  Equals = 61,
  A = 65,
  B = 66,
  C = 67,
  D = 68,
  E = 69, // ;)
  F = 70,
  G = 71,
  H = 72,
  I = 73,
  J = 74,
  K = 75,
  L = 76,
  M = 77,
  N = 78,
  O = 79,
  P = 80,
  Q = 81,
  R = 82,
  S = 83,
  T = 84,
  U = 85,
  V = 86,
  W = 87,
  X = 88,
  Y = 89,
  Z = 90,
  LeftBracket = 91,
  BackSlash = 92,
  RightBracket = 93,
  Accent = 96,
  // Non-ASCII
  Escape = 256,
  NumEnter,
  Backspace,
  Insert,
  Delete,
  Up,
  Down,
  Left,
  Right,
  PageUp,
  PageDown,
  Home,
  End,
  CapsLock,
  ScrollLock,
  NumLock,
  PrintScreen,
  Pause,
  Num0,
  Num1,
  Num2,
  Num3,
  Num4,
  Num5,
  Num6,
  Num7,
  Num8,
  Num9,
  F1,
  F2,
  F3,
  F4,
  F5,
  F6,
  F7,
  F8,
  F9,
  F10,
  F11,
  F12,
  F13,
  F14,
  F15,
  F16,
  F17,
  F18,
  F19,
  F20,
  F21,
  F22,
  F23,
  F24,
  F25,
  NumPeriod,
  NumComma,
  NumPlus,
  NumMinus,
  NumDivide,
  NumMultiply,
  NumEquals,
  LeftShift,
  LeftControl,
  LeftAlt,
  LeftSuper,
  RightShift,
  RightControl,
  RightAlt,
  RightSuper,
  Menu,
  Caret,
  AbntC1,
  AbntC2,
  Asterisk,
  At,
  Ax,
  Calculator,
  Colon,
  Convert,
  Kana,
  Kanji,
  Mail,
  MyComputer,
  NavigateForward,
  NavigateBackward,
  MediaPlayPause,
  MediaStop,
  MediaSelect,
  MediaNextTrack,
  MediaPrevTrack,
  VolumeDown,
  VolumeUp,
  VolumeMute,
  NoConvert,
  OEM102,
  Plus,
  Power,
  Sleep,
  Stop,
  SysRq,
  Underline,
  NoName,
  Wake,
  WebBack,
  WebFavorites,
  WebForward,
  WebHome,
  WebRefresh,
  WebSearch,
  WebStop,
  Yen,
  Copy,
  Paste,
  Cut,
}

impl From<VIRTUAL_KEY> for KeyCode {
  fn from(value: VIRTUAL_KEY) -> Self {
    // #[allow(unreachable_patterns)]
    match value {
      KeyboardAndMouse::VK_1 => KeyCode::_1,
      KeyboardAndMouse::VK_2 => KeyCode::_2,
      KeyboardAndMouse::VK_3 => KeyCode::_3,
      KeyboardAndMouse::VK_4 => KeyCode::_4,
      KeyboardAndMouse::VK_5 => KeyCode::_5,
      KeyboardAndMouse::VK_6 => KeyCode::_6,
      KeyboardAndMouse::VK_7 => KeyCode::_7,
      KeyboardAndMouse::VK_8 => KeyCode::_8,
      KeyboardAndMouse::VK_9 => KeyCode::_9,
      KeyboardAndMouse::VK_0 => KeyCode::_0,
      KeyboardAndMouse::VK_A => KeyCode::A,
      KeyboardAndMouse::VK_B => KeyCode::B,
      KeyboardAndMouse::VK_C => KeyCode::C,
      KeyboardAndMouse::VK_D => KeyCode::D,
      KeyboardAndMouse::VK_E => KeyCode::E,
      KeyboardAndMouse::VK_F => KeyCode::F,
      KeyboardAndMouse::VK_G => KeyCode::G,
      KeyboardAndMouse::VK_H => KeyCode::H,
      KeyboardAndMouse::VK_I => KeyCode::I,
      KeyboardAndMouse::VK_J => KeyCode::J,
      KeyboardAndMouse::VK_K => KeyCode::K,
      KeyboardAndMouse::VK_L => KeyCode::L,
      KeyboardAndMouse::VK_M => KeyCode::M,
      KeyboardAndMouse::VK_N => KeyCode::N,
      KeyboardAndMouse::VK_O => KeyCode::O,
      KeyboardAndMouse::VK_P => KeyCode::P,
      KeyboardAndMouse::VK_Q => KeyCode::Q,
      KeyboardAndMouse::VK_R => KeyCode::R,
      KeyboardAndMouse::VK_S => KeyCode::S,
      KeyboardAndMouse::VK_T => KeyCode::T,
      KeyboardAndMouse::VK_U => KeyCode::U,
      KeyboardAndMouse::VK_V => KeyCode::V,
      KeyboardAndMouse::VK_W => KeyCode::W,
      KeyboardAndMouse::VK_X => KeyCode::X,
      KeyboardAndMouse::VK_Y => KeyCode::Y,
      KeyboardAndMouse::VK_Z => KeyCode::Z,
      KeyboardAndMouse::VK_ESCAPE => KeyCode::Escape,
      KeyboardAndMouse::VK_F1 => KeyCode::F1,
      KeyboardAndMouse::VK_F2 => KeyCode::F2,
      KeyboardAndMouse::VK_F3 => KeyCode::F3,
      KeyboardAndMouse::VK_F4 => KeyCode::F4,
      KeyboardAndMouse::VK_F5 => KeyCode::F5,
      KeyboardAndMouse::VK_F6 => KeyCode::F6,
      KeyboardAndMouse::VK_F7 => KeyCode::F7,
      KeyboardAndMouse::VK_F8 => KeyCode::F8,
      KeyboardAndMouse::VK_F9 => KeyCode::F9,
      KeyboardAndMouse::VK_F10 => KeyCode::F10,
      KeyboardAndMouse::VK_F11 => KeyCode::F11,
      KeyboardAndMouse::VK_F12 => KeyCode::F12,
      KeyboardAndMouse::VK_F13 => KeyCode::F13,
      KeyboardAndMouse::VK_F14 => KeyCode::F14,
      KeyboardAndMouse::VK_F15 => KeyCode::F15,
      KeyboardAndMouse::VK_F16 => KeyCode::F16,
      KeyboardAndMouse::VK_F17 => KeyCode::F17,
      KeyboardAndMouse::VK_F18 => KeyCode::F18,
      KeyboardAndMouse::VK_F19 => KeyCode::F19,
      KeyboardAndMouse::VK_F20 => KeyCode::F20,
      KeyboardAndMouse::VK_F21 => KeyCode::F21,
      KeyboardAndMouse::VK_F22 => KeyCode::F22,
      KeyboardAndMouse::VK_F23 => KeyCode::F23,
      KeyboardAndMouse::VK_F24 => KeyCode::F24,
      KeyboardAndMouse::VK_SNAPSHOT => KeyCode::PrintScreen,
      KeyboardAndMouse::VK_SCROLL => KeyCode::ScrollLock,
      KeyboardAndMouse::VK_PAUSE => KeyCode::Pause,
      KeyboardAndMouse::VK_INSERT => KeyCode::Insert,
      KeyboardAndMouse::VK_HOME => KeyCode::Home,
      KeyboardAndMouse::VK_DELETE => KeyCode::Delete,
      KeyboardAndMouse::VK_END => KeyCode::End,
      KeyboardAndMouse::VK_NEXT => KeyCode::PageDown,
      KeyboardAndMouse::VK_PRIOR => KeyCode::PageUp,
      KeyboardAndMouse::VK_LEFT => KeyCode::Left,
      KeyboardAndMouse::VK_UP => KeyCode::Up,
      KeyboardAndMouse::VK_RIGHT => KeyCode::Right,
      KeyboardAndMouse::VK_DOWN => KeyCode::Down,
      KeyboardAndMouse::VK_BACK => KeyCode::Backspace,
      KeyboardAndMouse::VK_RETURN => KeyCode::Enter,
      KeyboardAndMouse::VK_SPACE => KeyCode::Space,
      //KeyboardAndMouse::VK_                    => KeyCode::Compose,
      //KeyboardAndMouse::VK_                    => KeyCode::Caret,
      KeyboardAndMouse::VK_NUMLOCK => KeyCode::NumLock,
      KeyboardAndMouse::VK_NUMPAD0 => KeyCode::Num0,
      KeyboardAndMouse::VK_NUMPAD1 => KeyCode::Num1,
      KeyboardAndMouse::VK_NUMPAD2 => KeyCode::Num2,
      KeyboardAndMouse::VK_NUMPAD3 => KeyCode::Num3,
      KeyboardAndMouse::VK_NUMPAD4 => KeyCode::Num4,
      KeyboardAndMouse::VK_NUMPAD5 => KeyCode::Num5,
      KeyboardAndMouse::VK_NUMPAD6 => KeyCode::Num6,
      KeyboardAndMouse::VK_NUMPAD7 => KeyCode::Num7,
      KeyboardAndMouse::VK_NUMPAD8 => KeyCode::Num8,
      KeyboardAndMouse::VK_NUMPAD9 => KeyCode::Num9,
      KeyboardAndMouse::VK_ADD => KeyCode::NumPlus,
      KeyboardAndMouse::VK_SUBTRACT => KeyCode::NumMinus,
      KeyboardAndMouse::VK_MULTIPLY => KeyCode::NumMultiply,
      KeyboardAndMouse::VK_DIVIDE => KeyCode::NumDivide,
      KeyboardAndMouse::VK_DECIMAL => KeyCode::NumPeriod,
      //KeyboardAndMouse::VK_COMMA               => KeyCode::NumComma,
      //KeyboardAndMouse::VK_ENTER               => KeyCode::NumEnter,
      //KeyboardAndMouse::VK_EQUALS              => KeyCode::NumEquals,
      KeyboardAndMouse::VK_ABNT_C1 => KeyCode::AbntC1,
      KeyboardAndMouse::VK_ABNT_C2 => KeyCode::AbntC2,
      KeyboardAndMouse::VK_OEM_7 => KeyCode::Apostrophe,
      KeyboardAndMouse::VK_APPS => KeyCode::Menu,
      //KeyboardAndMouse::VK_ASTERISK            => KeyCode::Asterisk,
      //KeyboardAndMouse::VK_AT                  => KeyCode::At,
      KeyboardAndMouse::VK_OEM_AX => KeyCode::Ax,
      KeyboardAndMouse::VK_OEM_5 => KeyCode::BackSlash,
      //KeyboardAndMouse::VK_LAUNCH_CALCULATOR   => KeyCode::Calculator,
      KeyboardAndMouse::VK_CAPITAL => KeyCode::CapsLock,
      //KeyboardAndMouse::VK_COLON               => KeyCode::Colon,
      KeyboardAndMouse::VK_OEM_COMMA => KeyCode::Comma,
      KeyboardAndMouse::VK_CONVERT => KeyCode::Convert,
      KeyboardAndMouse::VK_OEM_PLUS => KeyCode::Equals,
      KeyboardAndMouse::VK_OEM_3 => KeyCode::Accent,
      KeyboardAndMouse::VK_KANA => KeyCode::Kana,
      KeyboardAndMouse::VK_KANJI => KeyCode::Kanji,
      KeyboardAndMouse::VK_LMENU => KeyCode::LeftAlt,
      KeyboardAndMouse::VK_OEM_4 => KeyCode::LeftBracket,
      KeyboardAndMouse::VK_LCONTROL => KeyCode::LeftControl,
      KeyboardAndMouse::VK_LSHIFT => KeyCode::LeftShift,
      KeyboardAndMouse::VK_LWIN => KeyCode::LeftSuper,
      KeyboardAndMouse::VK_LAUNCH_MAIL => KeyCode::Mail,
      KeyboardAndMouse::VK_LAUNCH_MEDIA_SELECT => KeyCode::MediaSelect,
      KeyboardAndMouse::VK_MEDIA_STOP => KeyCode::MediaStop,
      KeyboardAndMouse::VK_OEM_MINUS => KeyCode::Minus,
      KeyboardAndMouse::VK_VOLUME_MUTE => KeyCode::VolumeMute,
      //KeyboardAndMouse::VK_MYCOMPUTER          => KeyCode::MyComputer,
      //KeyboardAndMouse::VK_BROWSER_FORWARD     => KeyCode::NavigateForward,
      //KeyboardAndMouse::VK_BROWSER_BACK        => KeyCode::NavigateBackward,
      KeyboardAndMouse::VK_MEDIA_NEXT_TRACK => KeyCode::MediaNextTrack,
      KeyboardAndMouse::VK_NONCONVERT => KeyCode::NoConvert,
      KeyboardAndMouse::VK_OEM_102 => KeyCode::OEM102,
      KeyboardAndMouse::VK_OEM_PERIOD => KeyCode::Period,
      KeyboardAndMouse::VK_MEDIA_PLAY_PAUSE => KeyCode::MediaPlayPause,
      //KeyboardAndMouse::VK_OEM_PLUS            => KeyCode::Plus,
      //KeyboardAndMouse::VK_POWER               => KeyCode::Power,
      KeyboardAndMouse::VK_MEDIA_PREV_TRACK => KeyCode::MediaPrevTrack,
      KeyboardAndMouse::VK_RMENU => KeyCode::RightAlt,
      KeyboardAndMouse::VK_OEM_6 => KeyCode::RightBracket,
      KeyboardAndMouse::VK_RCONTROL => KeyCode::RightControl,
      KeyboardAndMouse::VK_RSHIFT => KeyCode::RightShift,
      KeyboardAndMouse::VK_RWIN => KeyCode::RightSuper,
      KeyboardAndMouse::VK_OEM_1 => KeyCode::Semicolon,
      KeyboardAndMouse::VK_OEM_2 => KeyCode::ForwardSlash,
      KeyboardAndMouse::VK_SLEEP => KeyCode::Sleep,
      //KeyboardAndMouse::VK_STOP                => KeyCode::Stop,
      //KeyboardAndMouse::VK_SYSRQ               => KeyCode::SysRq,
      KeyboardAndMouse::VK_TAB => KeyCode::Tab,
      //KeyboardAndMouse::VK_UNDERLINE           => KeyCode::Underline,
      KeyboardAndMouse::VK_NONAME => KeyCode::NoName,
      KeyboardAndMouse::VK_VOLUME_DOWN => KeyCode::VolumeDown,
      KeyboardAndMouse::VK_VOLUME_UP => KeyCode::VolumeUp,
      //KeyboardAndMouse::VK_WAKE                => KeyCode::Wake,
      KeyboardAndMouse::VK_BROWSER_BACK => KeyCode::WebBack,
      KeyboardAndMouse::VK_BROWSER_FAVORITES => KeyCode::WebFavorites,
      KeyboardAndMouse::VK_BROWSER_FORWARD => KeyCode::WebForward,
      KeyboardAndMouse::VK_BROWSER_HOME => KeyCode::WebHome,
      KeyboardAndMouse::VK_BROWSER_REFRESH => KeyCode::WebRefresh,
      KeyboardAndMouse::VK_BROWSER_SEARCH => KeyCode::WebSearch,
      KeyboardAndMouse::VK_BROWSER_STOP => KeyCode::WebStop,
      //KeyboardAndMouse::VK_YEN                 => KeyCode::Yen,
      KeyboardAndMouse::VK_OEM_COPY => KeyCode::Copy,
      //KeyboardAndMouse::VK_OEM_PASTE           => KeyCode::Paste,
      //KeyboardAndMouse::VK_OEM_CUT             => KeyCode::Cut,
      _ => KeyCode::Unknown,
    }
  }
}

// pub struct KeyboardMessage {

// }
